export const FEED_WS_CONNECTION_START = 'FEED_WS_CONNECTION_START';
export const FEED_WS_CONNECTION_STOP = 'FEED_WS_CONNECTION_STOP';
export const SET_FEED_DATA = 'SET_FEED_DATA';
export const SET_FEED_WS_CONNECTION_STATUS = 'SET_FEED_WS_CONNECTION_STATUS';
