export const USER_ORDERS_WS_CONNECTION_START = 'USER_ORDERS_WS_CONNECTION_START';
export const USER_ORDERS_WS_CONNECTION_STOP = 'USER_ORDERS_WS_CONNECTION_STOP';
export const SET_USER_ORDERS_DATA = 'SET_USER_ORDERS_DATA';
export const SET_USER_ORDERS_WS_CONNECTION_STATUS = 'SET_USER_ORDERS_WS_CONNECTION_STATUS';
