export const GET_USER_SUCCESS: "GET_USER_SUCCESS" = "GET_USER_SUCCESS";
export const SET_AUTH_CHECKED: "SET_AUTH_CHECKED" = "SET_AUTH_CHECKED";

export const SET_BUN: "SET_BUN" = "SET_BUN";
export const ADD_FILLING: "ADD_FILLING" = "ADD_FILLING";
export const DELETE_FILLING: "DELETE_FILLING" = "DELETE_FILLING";
export const SORT_FILLINGS: "SORT_FILLINGS" = "SORT_FILLINGS";

export const GET_INGREDIENTS_REQUEST: "GET_INGREDIENTS_REQUEST" =
  "GET_INGREDIENTS_REQUEST";
export const GET_INGREDIENTS_SUCCESS: "GET_INGREDIENTS_SUCCESS" =
  "GET_INGREDIENTS_SUCCESS";
export const GET_INGREDIENTS_FAILED: "GET_INGREDIENTS_FAILED" =
  "GET_INGREDIENTS_FAILED";
export const SET_COUNTER: "SET_COUNTER" = "SET_COUNTER";
export const INCREASE_COUNTER: "INCREASE_COUNTER" = "INCREASE_COUNTER";
export const DECREASE_COUNTER: "DECREASE_COUNTER" = "DECREASE_COUNTER";
export const DELETE_COUNTER: "DELETE_COUNTER" = "DELETE_COUNTER";

export const FEED_WS_CONNECTION_START: "FEED_WS_CONNECTION_START" =
  "FEED_WS_CONNECTION_START";
export const FEED_WS_CONNECTION_STOP: "FEED_WS_CONNECTION_STOP" =
  "FEED_WS_CONNECTION_STOP";
export const SET_FEED_DATA: "SET_FEED_DATA" = "SET_FEED_DATA";
export const SET_FEED_WS_CONNECTION_STATUS: "SET_FEED_WS_CONNECTION_STATUS" =
  "SET_FEED_WS_CONNECTION_STATUS";

export const APPLY_ORDER_REQUEST: "APPLY_ORDER_REQUEST" = "APPLY_ORDER_REQUEST";
export const APPLY_ORDER_SUCCESS: "APPLY_ORDER_SUCCESS" = "APPLY_ORDER_SUCCESS";
export const APPLY_ORDER_FAILED: "APPLY_ORDER_FAILED" = "APPLY_ORDER_FAILED";

export const USER_ORDERS_WS_CONNECTION_START: "USER_ORDERS_WS_CONNECTION_START" =
  "USER_ORDERS_WS_CONNECTION_START";
export const USER_ORDERS_WS_CONNECTION_STOP: "USER_ORDERS_WS_CONNECTION_STOP" =
  "USER_ORDERS_WS_CONNECTION_STOP";
export const SET_USER_ORDERS_DATA: "SET_USER_ORDERS_DATA" =
  "SET_USER_ORDERS_DATA";
export const SET_USER_ORDERS_WS_CONNECTION_STATUS: "SET_USER_ORDERS_WS_CONNECTION_STATUS" =
  "SET_USER_ORDERS_WS_CONNECTION_STATUS";
